//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind_Generate
{
    using System;
    
    
    public class Categories
    {
        
        private System.Nullable<int> _CategoryID;
        
        private string _CategoryName;
        
        private string _Description;
        
        private byte[] _Picture;
        
        public System.Nullable<int> CategoryID
        {
            get
            {
                return _CategoryID;
            }
            set
            {
                _CategoryID=value;
            }
        }
        
        public string CategoryName
        {
            get
            {
                return _CategoryName;
            }
            set
            {
                _CategoryName=value;
            }
        }
        
        public string Description
        {
            get
            {
                return _Description;
            }
            set
            {
                _Description=value;
            }
        }
        
        public byte[] Picture
        {
            get
            {
                return _Picture;
            }
            set
            {
                _Picture=value;
            }
        }
    }
}
