//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind_Generate
{
    using System;
    
    
    public class Employees
    {
        
        private System.Nullable<int> _EmployeeID;
        
        private string _LastName;
        
        private string _FirstName;
        
        private string _Title;
        
        private string _TitleOfCourtesy;
        
        private System.Nullable<System.DateTime> _BirthDate;
        
        private System.Nullable<System.DateTime> _HireDate;
        
        private string _Address;
        
        private string _City;
        
        private string _Region;
        
        private string _PostalCode;
        
        private string _Country;
        
        private string _HomePhone;
        
        private string _Extension;
        
        private byte[] _Photo;
        
        private string _Notes;
        
        private System.Nullable<int> _ReportsTo;
        
        private string _PhotoPath;
        
        public System.Nullable<int> EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                _EmployeeID=value;
            }
        }
        
        public string LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                _LastName=value;
            }
        }
        
        public string FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                _FirstName=value;
            }
        }
        
        public string Title
        {
            get
            {
                return _Title;
            }
            set
            {
                _Title=value;
            }
        }
        
        public string TitleOfCourtesy
        {
            get
            {
                return _TitleOfCourtesy;
            }
            set
            {
                _TitleOfCourtesy=value;
            }
        }
        
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return _BirthDate;
            }
            set
            {
                _BirthDate=value;
            }
        }
        
        public System.Nullable<System.DateTime> HireDate
        {
            get
            {
                return _HireDate;
            }
            set
            {
                _HireDate=value;
            }
        }
        
        public string Address
        {
            get
            {
                return _Address;
            }
            set
            {
                _Address=value;
            }
        }
        
        public string City
        {
            get
            {
                return _City;
            }
            set
            {
                _City=value;
            }
        }
        
        public string Region
        {
            get
            {
                return _Region;
            }
            set
            {
                _Region=value;
            }
        }
        
        public string PostalCode
        {
            get
            {
                return _PostalCode;
            }
            set
            {
                _PostalCode=value;
            }
        }
        
        public string Country
        {
            get
            {
                return _Country;
            }
            set
            {
                _Country=value;
            }
        }
        
        public string HomePhone
        {
            get
            {
                return _HomePhone;
            }
            set
            {
                _HomePhone=value;
            }
        }
        
        public string Extension
        {
            get
            {
                return _Extension;
            }
            set
            {
                _Extension=value;
            }
        }
        
        public byte[] Photo
        {
            get
            {
                return _Photo;
            }
            set
            {
                _Photo=value;
            }
        }
        
        public string Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                _Notes=value;
            }
        }
        
        public System.Nullable<int> ReportsTo
        {
            get
            {
                return _ReportsTo;
            }
            set
            {
                _ReportsTo=value;
            }
        }
        
        public string PhotoPath
        {
            get
            {
                return _PhotoPath;
            }
            set
            {
                _PhotoPath=value;
            }
        }
    }
}
