//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind_Generate
{
    using System;
    
    
    public class Products
    {
        
        private System.Nullable<int> _ProductID;
        
        private string _ProductName;
        
        private System.Nullable<int> _SupplierID;
        
        private System.Nullable<int> _CategoryID;
        
        private string _QuantityPerUnit;
        
        private System.Nullable<decimal> _UnitPrice;
        
        private System.Nullable<short> _UnitsInStock;
        
        private System.Nullable<short> _UnitsOnOrder;
        
        private System.Nullable<short> _ReorderLevel;
        
        private System.Nullable<bool> _Discontinued;
        
        public System.Nullable<int> ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                _ProductID=value;
            }
        }
        
        public string ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                _ProductName=value;
            }
        }
        
        public System.Nullable<int> SupplierID
        {
            get
            {
                return _SupplierID;
            }
            set
            {
                _SupplierID=value;
            }
        }
        
        public System.Nullable<int> CategoryID
        {
            get
            {
                return _CategoryID;
            }
            set
            {
                _CategoryID=value;
            }
        }
        
        public string QuantityPerUnit
        {
            get
            {
                return _QuantityPerUnit;
            }
            set
            {
                _QuantityPerUnit=value;
            }
        }
        
        public System.Nullable<decimal> UnitPrice
        {
            get
            {
                return _UnitPrice;
            }
            set
            {
                _UnitPrice=value;
            }
        }
        
        public System.Nullable<short> UnitsInStock
        {
            get
            {
                return _UnitsInStock;
            }
            set
            {
                _UnitsInStock=value;
            }
        }
        
        public System.Nullable<short> UnitsOnOrder
        {
            get
            {
                return _UnitsOnOrder;
            }
            set
            {
                _UnitsOnOrder=value;
            }
        }
        
        public System.Nullable<short> ReorderLevel
        {
            get
            {
                return _ReorderLevel;
            }
            set
            {
                _ReorderLevel=value;
            }
        }
        
        public System.Nullable<bool> Discontinued
        {
            get
            {
                return _Discontinued;
            }
            set
            {
                _Discontinued=value;
            }
        }
    }
}
